### ISSUE TITLE
我想反馈的建议基本上都在这里了

### ISSUE THREAD

**Issue by lgc2333** [DreamCherish/BDShousekeeper#3]
如题 易语言小白一枚 不喜勿喷
十分感谢作者搬运插件到小栗子，为我们腐竹提供了群聊机器人的解决方案，感激不尽！
看图吧
![QQ截图20200829234212](https://user-images.githubusercontent.com/59048777/91640718-3a9ff200-ea52-11ea-89fe-7f2c1e6d469d.png)
![QQ截图20200829234246](https://user-images.githubusercontent.com/59048777/91640729-48ee0e00-ea52-11ea-9449-27fbb91e8630.png)
![QQ截图20200829234305](https://user-images.githubusercontent.com/59048777/91640731-4c819500-ea52-11ea-8efc-a8bf891f5c82.png)

**Comment by lgc2333** [comment]
贴上瞎写的代码

[新建文本文档.txt](https://github.com/DreamCherish/BDShousekeeper/files/5145507/default.txt)

**Comment by DreamCherish** [comment]
前面反馈的，其实代码差不多就是这样，转发自己的消息会修复，因为框架是多Q同框架，所以会接收，转发到服务器的api原来测试应该是没问题，因为输出空数据所以自动输出为QQ号

**Comment by lgc2333** [comment]
> 前面反馈的，其实代码差不多就是这样，转发自己的消息会修复，因为框架是多Q同框架，所以会接收，转发到服务器的api原来测试应该是没问题，因为输出空数据所以自动输出为QQ号

还有那个转发到服务器消息的那个换行符问题希望可以看一下 感谢大佬！

**Comment by DreamCherish** [comment]
应该都解决了，原来换行是支持的，是框架编码的原因，其他都没问题，谢谢反馈
